-- RC6: editable association records retain their original compound keys and gain stable UI identities.
alter table app.class_students add column if not exists id uuid not null default gen_random_uuid();
create unique index class_students_ui_identity on app.class_students(tenant_id,id);
alter table app.class_students add column if not exists created_at timestamptz not null default clock_timestamp();
alter table app.class_students add column if not exists updated_at timestamptz not null default clock_timestamp();
alter table app.class_students add column if not exists row_version bigint not null default 1;
create trigger class_students_rc6_metadata before update on app.class_students for each row execute function app.set_updated_metadata();
alter table app.class_staff add column if not exists id uuid not null default gen_random_uuid();
create unique index class_staff_ui_identity on app.class_staff(tenant_id,id);
alter table app.class_staff add column if not exists created_at timestamptz not null default clock_timestamp();
alter table app.class_staff add column if not exists updated_at timestamptz not null default clock_timestamp();
alter table app.class_staff add column if not exists row_version bigint not null default 1;
create trigger class_staff_rc6_metadata before update on app.class_staff for each row execute function app.set_updated_metadata();
alter table app.event_participants add column if not exists id uuid not null default gen_random_uuid();
create unique index event_participants_ui_identity on app.event_participants(tenant_id,id);
alter table app.event_participants add column if not exists created_at timestamptz not null default clock_timestamp();
alter table app.event_participants add column if not exists updated_at timestamptz not null default clock_timestamp();
alter table app.event_participants add column if not exists row_version bigint not null default 1;
create trigger event_participants_rc6_metadata before update on app.event_participants for each row execute function app.set_updated_metadata();
alter table app.student_families add column if not exists id uuid not null default gen_random_uuid();
create unique index student_families_ui_identity on app.student_families(tenant_id,id);
alter table app.student_families add column if not exists created_at timestamptz not null default clock_timestamp();
alter table app.student_families add column if not exists updated_at timestamptz not null default clock_timestamp();
alter table app.student_families add column if not exists row_version bigint not null default 1;
create trigger student_families_rc6_metadata before update on app.student_families for each row execute function app.set_updated_metadata();
alter table app.portal_contacts add column if not exists id uuid not null default gen_random_uuid();
create unique index portal_contacts_ui_identity on app.portal_contacts(tenant_id,id);
alter table app.portal_contacts add column if not exists created_at timestamptz not null default clock_timestamp();
alter table app.portal_contacts add column if not exists updated_at timestamptz not null default clock_timestamp();
alter table app.portal_contacts add column if not exists row_version bigint not null default 1;
create trigger portal_contacts_rc6_metadata before update on app.portal_contacts for each row execute function app.set_updated_metadata();
