/** @fileoverview Shared, bounded field definitions for RC6 school workflows; SQL identifiers are build-time constants. */
import { z } from 'zod';

export interface RoadmapField {
  readonly key: string;
  readonly column: string;
  readonly label: string;
  readonly type: string;
  readonly required: boolean;
  readonly reference?: string;
  readonly options?: readonly string[];
  readonly defaultValue?: unknown;
  readonly min?: number;
  readonly max?: number;
  readonly signed?: boolean;
}
export interface RoadmapResource {
  readonly name: string;
  readonly table: string;
  readonly module: string;
  readonly title: string;
  readonly singular: string;
  readonly fields: readonly RoadmapField[];
  readonly existing: boolean;
  readonly workflow?: boolean;
  readonly adminOnly?: boolean;
  readonly assignedOnly?: boolean;
}
export const roadmapResources: readonly RoadmapResource[] = [
  {
    name: 'invoice-allocations',
    table: 'invoice_allocations',
    module: 'finance',
    title: 'Invoice responsibility',
    singular: 'invoice allocation',
    fields: [
      {
        key: 'invoiceId',
        column: 'invoice_id',
        label: 'Invoice',
        type: 'reference',
        required: true,
        reference: 'invoices',
      },
      {
        key: 'guardianId',
        column: 'guardian_id',
        label: 'Responsible guardian',
        type: 'reference',
        required: true,
        reference: 'guardians',
      },
      {
        key: 'studentId',
        column: 'student_id',
        label: 'Student',
        type: 'reference',
        required: true,
        reference: 'students',
      },
      {
        key: 'amount',
        column: 'amount',
        label: 'Allocated amount (including tax)',
        type: 'money',
        required: true,
      },
    ],
    existing: false,
  },
  {
    name: 'guardians',
    table: 'guardians',
    module: 'families',
    title: 'Guardians',
    singular: 'guardian',
    fields: [
      {
        key: 'firstName',
        column: 'first_name',
        label: 'First name',
        type: 'text',
        required: true,
      },
      {
        key: 'lastName',
        column: 'last_name',
        label: 'Last name',
        type: 'text',
        required: true,
      },
      {
        key: 'userId',
        column: 'user_id',
        label: 'Portal account',
        type: 'reference',
        required: false,
        reference: 'users',
      },
      {
        key: 'email',
        column: 'email',
        label: 'Email',
        type: 'email',
        required: false,
      },
      {
        key: 'mobilePhone',
        column: 'mobile_phone',
        label: 'Mobile phone',
        type: 'text',
        required: false,
      },
      {
        key: 'postalAddress',
        column: 'postal_address',
        label: 'Address',
        type: 'textarea',
        required: false,
      },
    ],
    existing: true,
    adminOnly: true,
  },
  {
    name: 'class-rosters',
    table: 'class_students',
    module: 'classes',
    title: 'Class rosters',
    singular: 'class roster',
    fields: [
      {
        key: 'classId',
        column: 'class_id',
        label: 'Class',
        type: 'reference',
        required: true,
        reference: 'classes',
      },
      {
        key: 'studentId',
        column: 'student_id',
        label: 'Student',
        type: 'reference',
        required: true,
        reference: 'students',
      },
      {
        key: 'enrolledFrom',
        column: 'enrolled_from',
        label: 'From',
        type: 'date',
        required: true,
      },
      {
        key: 'enrolledUntil',
        column: 'enrolled_until',
        label: 'Until',
        type: 'date',
        required: false,
      },
      {
        key: 'status',
        column: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: ['active', 'withdrawn', 'completed'],
        defaultValue: 'active',
      },
    ],
    existing: true,
    adminOnly: false,
  },
  {
    name: 'class-teachers',
    table: 'class_staff',
    module: 'classes',
    title: 'Class teachers',
    singular: 'class teacher',
    fields: [
      {
        key: 'classId',
        column: 'class_id',
        label: 'Class',
        type: 'reference',
        required: true,
        reference: 'classes',
      },
      {
        key: 'staffId',
        column: 'staff_id',
        label: 'Staff',
        type: 'reference',
        required: true,
        reference: 'staff',
      },
      {
        key: 'role',
        column: 'role',
        label: 'Role',
        type: 'select',
        required: true,
        options: ['teacher', 'assistant', 'coordinator'],
        defaultValue: 'teacher',
      },
    ],
    existing: true,
    adminOnly: false,
  },
  {
    name: 'timetable-entries',
    table: 'timetable_entries',
    module: 'timetables',
    title: 'Timetable entries',
    singular: 'timetable entrie',
    fields: [
      {
        key: 'timetableSetId',
        column: 'timetable_set_id',
        label: 'Timetable',
        type: 'reference',
        required: true,
        reference: 'timetables',
      },
      {
        key: 'periodId',
        column: 'period_id',
        label: 'Session',
        type: 'reference',
        required: true,
        reference: 'bell-periods',
      },
      {
        key: 'classId',
        column: 'class_id',
        label: 'Class',
        type: 'reference',
        required: false,
        reference: 'classes',
      },
      {
        key: 'activityId',
        column: 'activity_id',
        label: 'Activity',
        type: 'reference',
        required: false,
        reference: 'activities',
      },
      {
        key: 'roomId',
        column: 'room_id',
        label: 'Room',
        type: 'reference',
        required: false,
        reference: 'rooms',
      },
      {
        key: 'supervisingStaffId',
        column: 'supervising_staff_id',
        label: 'Staff',
        type: 'reference',
        required: false,
        reference: 'staff',
      },
    ],
    existing: true,
    adminOnly: false,
  },
  {
    name: 'event-participants',
    table: 'event_participants',
    module: 'events',
    title: 'Event participants',
    singular: 'event participant',
    fields: [
      {
        key: 'eventId',
        column: 'event_id',
        label: 'Event',
        type: 'reference',
        required: true,
        reference: 'events',
      },
      {
        key: 'studentId',
        column: 'student_id',
        label: 'Student',
        type: 'reference',
        required: true,
        reference: 'students',
      },
      {
        key: 'status',
        column: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: ['invited', 'accepted', 'declined', 'waitlisted', 'attended'],
        defaultValue: 'invited',
      },
    ],
    existing: true,
    adminOnly: false,
  },
  {
    name: 'grade-results',
    table: 'grade_results',
    module: 'grades',
    title: 'Grade results',
    singular: 'grade result',
    fields: [
      {
        key: 'assessmentId',
        column: 'assessment_id',
        label: 'Assessment',
        type: 'reference',
        required: true,
        reference: 'assessments',
      },
      {
        key: 'studentId',
        column: 'student_id',
        label: 'Student',
        type: 'reference',
        required: true,
        reference: 'students',
      },
      {
        key: 'score',
        column: 'score',
        label: 'Score',
        type: 'money',
        required: false,
      },
      {
        key: 'gradeCode',
        column: 'grade_code',
        label: 'Grade',
        type: 'text',
        required: false,
      },
      {
        key: 'feedback',
        column: 'feedback',
        label: 'Feedback',
        type: 'textarea',
        required: false,
      },
      {
        key: 'status',
        column: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: ['draft', 'moderation', 'published', 'withheld'],
        defaultValue: 'draft',
      },
    ],
    existing: true,
    adminOnly: false,
  },
  {
    name: 'attendance-sessions',
    table: 'attendance_sessions',
    module: 'attendance',
    title: 'Attendance sessions',
    singular: 'attendance session',
    fields: [
      {
        key: 'campusId',
        column: 'campus_id',
        label: 'Campus',
        type: 'reference',
        required: true,
        reference: 'campuses',
      },
      {
        key: 'sessionDate',
        column: 'session_date',
        label: 'School date',
        type: 'date',
        required: true,
      },
      {
        key: 'periodId',
        column: 'period_id',
        label: 'Session',
        type: 'reference',
        required: false,
        reference: 'bell-periods',
      },
      {
        key: 'classId',
        column: 'class_id',
        label: 'Class',
        type: 'reference',
        required: false,
        reference: 'classes',
      },
      {
        key: 'activityId',
        column: 'activity_id',
        label: 'Activity',
        type: 'reference',
        required: false,
        reference: 'activities',
      },
      {
        key: 'sessionLabel',
        column: 'session_label',
        label: 'Roll label',
        type: 'text',
        required: true,
      },
      {
        key: 'status',
        column: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: ['planned', 'open'],
        defaultValue: 'planned',
      },
    ],
    existing: true,
    adminOnly: false,
  },
  {
    name: 'family-students',
    table: 'student_families',
    module: 'families',
    title: 'Family students',
    singular: 'family student',
    fields: [
      {
        key: 'studentId',
        column: 'student_id',
        label: 'Student',
        type: 'reference',
        required: true,
        reference: 'students',
      },
      {
        key: 'familyId',
        column: 'family_id',
        label: 'Family',
        type: 'reference',
        required: true,
        reference: 'families',
      },
      {
        key: 'isPrimaryHousehold',
        column: 'is_primary_household',
        label: 'Primary family',
        type: 'boolean',
        required: false,
        defaultValue: true,
      },
    ],
    existing: true,
    adminOnly: true,
  },
  {
    name: 'portal-contacts',
    table: 'portal_contacts',
    module: 'management',
    title: 'Portal contacts',
    singular: 'portal contact',
    fields: [
      {
        key: 'campusId',
        column: 'campus_id',
        label: 'Campus',
        type: 'reference',
        required: false,
        reference: 'campuses',
      },
      {
        key: 'role',
        column: 'role',
        label: 'Role',
        type: 'select',
        required: true,
        options: ['pastoral', 'duty_of_care', 'nurse', 'finance', 'support'],
        defaultValue: 'support',
      },
      {
        key: 'displayName',
        column: 'display_name',
        label: 'Name',
        type: 'text',
        required: true,
      },
      {
        key: 'email',
        column: 'email',
        label: 'Email',
        type: 'email',
        required: false,
      },
      {
        key: 'phone',
        column: 'phone',
        label: 'Phone',
        type: 'text',
        required: false,
      },
    ],
    existing: true,
    adminOnly: true,
  },
  {
    name: 'campuses',
    table: 'campuses',
    module: 'management',
    title: 'Campuses',
    singular: 'campus',
    fields: [
      {
        key: 'code',
        label: 'Code',
        type: 'text',
        required: true,
        column: 'code',
      },
      {
        key: 'name',
        label: 'Name',
        type: 'text',
        required: true,
        column: 'name',
      },
      {
        key: 'timezone',
        label: 'Time zone',
        type: 'text',
        required: true,
        defaultValue: 'Australia/Melbourne',
        column: 'timezone',
      },
      {
        key: 'active',
        label: 'Active',
        type: 'boolean',
        required: false,
        defaultValue: true,
        column: 'active',
      },
    ],
    existing: true,
  },
  {
    name: 'academic-years',
    table: 'academic_years',
    module: 'management',
    title: 'Academic years',
    singular: 'academic year',
    fields: [
      {
        key: 'name',
        label: 'Name',
        type: 'text',
        required: true,
        column: 'name',
      },
      {
        key: 'startsOn',
        label: 'Starts',
        type: 'date',
        required: true,
        column: 'starts_on',
      },
      {
        key: 'endsOn',
        label: 'Ends',
        type: 'date',
        required: true,
        column: 'ends_on',
      },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: ['planned', 'active', 'closed'],
        defaultValue: 'planned',
        column: 'status',
      },
    ],
    existing: true,
  },
  {
    name: 'terms',
    table: 'terms',
    module: 'management',
    title: 'Term dates',
    singular: 'term',
    fields: [
      {
        key: 'academicYearId',
        label: 'Academic year',
        type: 'reference',
        required: true,
        reference: 'academic-years',
        column: 'academic_year_id',
      },
      {
        key: 'name',
        label: 'Name',
        type: 'text',
        required: true,
        column: 'name',
      },
      {
        key: 'sequenceNumber',
        label: 'Term number',
        type: 'number',
        required: true,
        min: 1,
        max: 12,
        column: 'sequence_number',
      },
      {
        key: 'startsOn',
        label: 'Starts',
        type: 'date',
        required: true,
        column: 'starts_on',
      },
      {
        key: 'endsOn',
        label: 'Ends',
        type: 'date',
        required: true,
        column: 'ends_on',
      },
    ],
    existing: true,
  },
  {
    name: 'bell-periods',
    table: 'timetable_periods',
    module: 'management',
    title: 'Session times',
    singular: 'session',
    fields: [
      {
        key: 'timetableSetId',
        label: 'Timetable',
        type: 'reference',
        required: true,
        reference: 'timetables',
        column: 'timetable_set_id',
      },
      {
        key: 'weekday',
        label: 'Day',
        type: 'select',
        required: true,
        options: ['1', '2', '3', '4', '5', '6', '7'],
        defaultValue: '1',
        column: 'weekday',
      },
      {
        key: 'periodCode',
        label: 'Session label',
        type: 'text',
        required: true,
        column: 'period_code',
      },
      {
        key: 'sequenceNumber',
        label: 'Session order',
        type: 'number',
        required: true,
        min: 0,
        max: 50,
        column: 'sequence_number',
      },
      {
        key: 'startsAt',
        label: 'Starts',
        type: 'time',
        required: true,
        column: 'starts_at',
      },
      {
        key: 'endsAt',
        label: 'Ends',
        type: 'time',
        required: true,
        column: 'ends_at',
      },
    ],
    existing: true,
  },
  {
    name: 'important-dates',
    table: 'important_dates',
    module: 'management',
    title: 'Important dates',
    singular: 'important date',
    fields: [
      {
        key: 'title',
        label: 'Title',
        type: 'text',
        required: true,
        column: 'title',
      },
      {
        key: 'campusId',
        label: 'Campus (empty means whole school)',
        type: 'reference',
        required: false,
        reference: 'campuses',
        column: 'campus_id',
      },
      {
        key: 'startsOn',
        label: 'First date',
        type: 'date',
        required: true,
        column: 'starts_on',
      },
      {
        key: 'endsOn',
        label: 'Last date',
        type: 'date',
        required: true,
        column: 'ends_on',
      },
      {
        key: 'action',
        label: 'Class action',
        type: 'select',
        required: true,
        options: ['information', 'no_classes', 'no_classes_for_years'],
        defaultValue: 'information',
        column: 'action',
      },
      {
        key: 'yearLevels',
        label: 'Affected year levels',
        type: 'tags',
        required: false,
        column: 'year_levels',
      },
      {
        key: 'audience',
        label: 'Visible to',
        type: 'select',
        required: true,
        options: ['all', 'staff', 'parents', 'students'],
        defaultValue: 'all',
        column: 'audience',
      },
    ],
    existing: false,
  },
  {
    name: 'school-groups',
    table: 'school_groups',
    module: 'management',
    title: 'Student & staff groups',
    singular: 'group',
    fields: [
      {
        key: 'name',
        label: 'Group name',
        type: 'text',
        required: true,
        column: 'name',
      },
      {
        key: 'kind',
        label: 'Group type',
        type: 'select',
        required: true,
        options: ['students', 'staff', 'mixed'],
        defaultValue: 'students',
        column: 'kind',
      },
      {
        key: 'description',
        label: 'Description',
        type: 'textarea',
        required: false,
        column: 'description',
      },
      {
        key: 'departmentId',
        label: 'Department',
        type: 'reference',
        required: false,
        reference: 'departments',
        column: 'department_id',
      },
      {
        key: 'yearLevels',
        label: 'Include year levels',
        type: 'tags',
        required: false,
        column: 'year_levels',
      },
      {
        key: 'genders',
        label: 'Include gender values',
        type: 'tags',
        required: false,
        column: 'genders',
      },
      {
        key: 'campusId',
        label: 'Campus',
        type: 'reference',
        required: false,
        reference: 'campuses',
        column: 'campus_id',
      },
    ],
    existing: false,
  },
  {
    name: 'group-members',
    table: 'group_members',
    module: 'management',
    title: 'Group membership',
    singular: 'member',
    fields: [
      {
        key: 'groupId',
        label: 'Group',
        type: 'reference',
        required: true,
        reference: 'school-groups',
        column: 'group_id',
      },
      {
        key: 'userId',
        label: 'User',
        type: 'reference',
        required: false,
        reference: 'users',
        column: 'user_id',
      },
      {
        key: 'studentId',
        label: 'Student',
        type: 'reference',
        required: false,
        reference: 'students',
        column: 'student_id',
      },
      {
        key: 'staffId',
        label: 'Staff member',
        type: 'reference',
        required: false,
        reference: 'staff',
        column: 'staff_id',
      },
      {
        key: 'role',
        label: 'Group role',
        type: 'select',
        required: true,
        options: ['member', 'manager'],
        defaultValue: 'member',
        column: 'role',
      },
      {
        key: 'validFrom',
        label: 'Access starts',
        type: 'datetime-local',
        required: true,
        column: 'valid_from',
      },
      {
        key: 'validUntil',
        label: 'Access ends',
        type: 'datetime-local',
        required: false,
        column: 'valid_until',
      },
    ],
    existing: false,
  },
  {
    name: 'departments',
    table: 'departments',
    module: 'management',
    title: 'Departments',
    singular: 'department',
    fields: [
      {
        key: 'code',
        label: 'Code',
        type: 'text',
        required: true,
        column: 'code',
      },
      {
        key: 'name',
        label: 'Name',
        type: 'text',
        required: true,
        column: 'name',
      },
      {
        key: 'active',
        label: 'Active',
        type: 'boolean',
        required: false,
        defaultValue: true,
        column: 'active',
      },
    ],
    existing: true,
  },
  {
    name: 'venues',
    table: 'venues',
    module: 'events',
    title: 'Venues & emergency contacts',
    singular: 'venue',
    fields: [
      {
        key: 'name',
        label: 'Venue name',
        type: 'text',
        required: true,
        column: 'name',
      },
      {
        key: 'address',
        label: 'Address',
        type: 'textarea',
        required: true,
        column: 'address',
      },
      {
        key: 'emergencyPhone',
        label: 'Emergency number',
        type: 'text',
        required: false,
        defaultValue: '000',
        column: 'emergency_phone',
      },
      {
        key: 'hospital',
        label: 'Nearest hospital',
        type: 'textarea',
        required: false,
        column: 'hospital',
      },
      {
        key: 'police',
        label: 'Nearest police station',
        type: 'textarea',
        required: false,
        column: 'police',
      },
      {
        key: 'emergencyPlan',
        label: 'Emergency plan',
        type: 'textarea',
        required: false,
        column: 'emergency_plan',
      },
      {
        key: 'accessible',
        label: 'Accessible',
        type: 'boolean',
        required: false,
        defaultValue: true,
        column: 'accessible',
      },
    ],
    existing: false,
  },
  {
    name: 'event-plans',
    table: 'event_plans',
    module: 'events',
    title: 'Event proposals & planning',
    singular: 'event plan',
    fields: [
      {
        key: 'eventId',
        label: 'Event',
        type: 'reference',
        required: true,
        reference: 'events',
        column: 'event_id',
      },
      {
        key: 'venueId',
        label: 'Venue',
        type: 'reference',
        required: true,
        reference: 'venues',
        column: 'venue_id',
      },
      {
        key: 'title',
        label: 'Plan title',
        type: 'text',
        required: true,
        column: 'title',
      },
      {
        key: 'studentActivities',
        label: 'Student activities',
        type: 'textarea',
        required: true,
        column: 'student_activities',
      },
      {
        key: 'staffActivities',
        label: 'Staff activities',
        type: 'textarea',
        required: true,
        column: 'staff_activities',
      },
      {
        key: 'overnight',
        label: 'Overnight stay',
        type: 'boolean',
        required: false,
        column: 'overnight',
      },
      {
        key: 'accommodation',
        label: 'Accommodation',
        type: 'textarea',
        required: false,
        column: 'accommodation',
      },
      {
        key: 'priorVisit',
        label: 'Staff have visited before',
        type: 'boolean',
        required: false,
        column: 'prior_visit',
      },
      {
        key: 'studentCount',
        label: 'Number of students',
        type: 'number',
        required: true,
        min: 1,
        max: 100000,
        column: 'student_count',
      },
      {
        key: 'staffCount',
        label: 'Number of supervising staff',
        type: 'number',
        required: true,
        min: 1,
        max: 10000,
        column: 'staff_count',
      },
      {
        key: 'studentsPerStaff',
        label: 'Maximum students per staff member',
        type: 'number',
        required: true,
        min: 1,
        max: 100,
        column: 'students_per_staff',
      },
      {
        key: 'hazards',
        label: 'Activities / hazards',
        type: 'tags',
        required: false,
        options: [
          'water',
          'harness',
          'sport',
          'transport',
          'overnight',
          'remote',
          'heat',
          'food',
          'medical',
        ],
        column: 'hazards',
      },
      {
        key: 'budgetId',
        label: 'Budget',
        type: 'reference',
        required: false,
        reference: 'budgets',
        column: 'budget_id',
      },
      {
        key: 'accountId',
        label: 'GL account',
        type: 'reference',
        required: false,
        reference: 'finance-accounts',
        column: 'account_id',
      },
      {
        key: 'returnToWorkChecked',
        label: 'Staff restrictions checked with authorised HR',
        type: 'boolean',
        required: false,
        column: 'return_to_work_checked',
      },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: ['draft', 'submitted', 'risk_review', 'approved', 'rejected', 'completed'],
        defaultValue: 'draft',
        column: 'status',
      },
      {
        key: 'planningPrompts',
        column: 'planning_prompts',
        label: 'Planning prompts and review notes',
        type: 'textarea',
        required: false,
      },
    ],
    existing: false,
    workflow: true,
  },
  {
    name: 'event-templates',
    table: 'event_templates',
    module: 'events',
    title: 'Event templates',
    singular: 'template',
    fields: [
      {
        key: 'name',
        label: 'Template name',
        type: 'text',
        required: true,
        column: 'name',
      },
      {
        key: 'studentActivities',
        label: 'Student activities',
        type: 'textarea',
        required: false,
        column: 'student_activities',
      },
      {
        key: 'staffActivities',
        label: 'Staff activities',
        type: 'textarea',
        required: false,
        column: 'staff_activities',
      },
      {
        key: 'hazards',
        label: 'Common hazards',
        type: 'tags',
        required: false,
        column: 'hazards',
      },
      {
        key: 'controlPrompts',
        label: 'Planning prompts',
        type: 'textarea',
        required: false,
        column: 'control_prompts',
      },
      {
        key: 'studentsPerStaff',
        label: 'Maximum students per staff member',
        type: 'number',
        required: true,
        min: 1,
        max: 100,
        column: 'students_per_staff',
      },
      {
        key: 'overnight',
        label: 'Overnight',
        type: 'boolean',
        required: false,
        column: 'overnight',
      },
    ],
    existing: false,
  },
  {
    name: 'event-risks',
    table: 'event_risks',
    module: 'events',
    title: 'Event risk assessments',
    singular: 'risk assessment',
    fields: [
      {
        key: 'eventPlanId',
        label: 'Event plan',
        type: 'reference',
        required: true,
        reference: 'event-plans',
        column: 'event_plan_id',
      },
      {
        key: 'hazard',
        label: 'Specific hazard',
        type: 'text',
        required: true,
        column: 'hazard',
      },
      {
        key: 'peopleAtRisk',
        label: 'Who may be harmed',
        type: 'textarea',
        required: true,
        column: 'people_at_risk',
      },
      {
        key: 'likelihood',
        label: 'Likelihood (1\u20135)',
        type: 'number',
        required: true,
        min: 1,
        max: 5,
        column: 'likelihood',
      },
      {
        key: 'impact',
        label: 'Impact (1\u20135)',
        type: 'number',
        required: true,
        min: 1,
        max: 5,
        column: 'impact',
      },
      {
        key: 'controls',
        label: 'Control measures',
        type: 'textarea',
        required: true,
        column: 'controls',
      },
      {
        key: 'residualLikelihood',
        label: 'Residual likelihood (1\u20135)',
        type: 'number',
        required: true,
        min: 1,
        max: 5,
        column: 'residual_likelihood',
      },
      {
        key: 'residualImpact',
        label: 'Residual impact (1\u20135)',
        type: 'number',
        required: true,
        min: 1,
        max: 5,
        column: 'residual_impact',
      },
      {
        key: 'ownerUserId',
        label: 'Responsible staff member',
        type: 'reference',
        required: true,
        reference: 'users',
        column: 'owner_user_id',
      },
      {
        key: 'reviewOn',
        label: 'Review date',
        type: 'date',
        required: true,
        column: 'review_on',
      },
    ],
    existing: false,
  },
  {
    name: 'approval-streams',
    table: 'approval_streams',
    module: 'risk',
    title: 'Risk approval streams',
    singular: 'approval stream',
    fields: [
      {
        key: 'name',
        label: 'Stream name',
        type: 'text',
        required: true,
        column: 'name',
      },
      {
        key: 'hazards',
        label: 'Applies to hazards',
        type: 'tags',
        required: false,
        column: 'hazards',
      },
      {
        key: 'minimumRiskScore',
        label: 'Minimum risk score',
        type: 'number',
        required: true,
        min: 1,
        max: 25,
        column: 'minimum_risk_score',
      },
      {
        key: 'approverGroupId',
        label: 'Approver group',
        type: 'reference',
        required: true,
        reference: 'school-groups',
        column: 'approver_group_id',
      },
      {
        key: 'sequenceNumber',
        label: 'Approval order',
        type: 'number',
        required: true,
        min: 1,
        max: 20,
        column: 'sequence_number',
      },
      {
        key: 'active',
        label: 'Active',
        type: 'boolean',
        required: false,
        defaultValue: true,
        column: 'active',
      },
    ],
    existing: false,
  },
  {
    name: 'event-access',
    table: 'event_access',
    module: 'events',
    title: 'Scheduled medical access',
    singular: 'access window',
    fields: [
      {
        key: 'eventId',
        label: 'Event',
        type: 'reference',
        required: true,
        reference: 'events',
        column: 'event_id',
      },
      {
        key: 'userId',
        label: 'Assigned staff member',
        type: 'reference',
        required: true,
        reference: 'users',
        column: 'user_id',
      },
      {
        key: 'validFrom',
        label: 'Access starts',
        type: 'datetime-local',
        required: true,
        column: 'valid_from',
      },
      {
        key: 'validUntil',
        label: 'Access ends',
        type: 'datetime-local',
        required: true,
        column: 'valid_until',
      },
      {
        key: 'allDay',
        label: '24 hour access',
        type: 'boolean',
        required: false,
        defaultValue: true,
        column: 'all_day',
      },
      {
        key: 'dailyFrom',
        label: 'Daily start',
        type: 'time',
        required: false,
        column: 'daily_from',
      },
      {
        key: 'dailyUntil',
        label: 'Daily end',
        type: 'time',
        required: false,
        column: 'daily_until',
      },
      {
        key: 'timezone',
        label: 'Time zone',
        type: 'text',
        required: true,
        defaultValue: 'Australia/Melbourne',
        column: 'timezone',
      },
      {
        key: 'reason',
        label: 'Access purpose',
        type: 'textarea',
        required: true,
        column: 'reason',
      },
    ],
    existing: false,
    adminOnly: true,
  },
  {
    name: 'risk-incidents',
    table: 'risk_incidents',
    module: 'risk',
    title: 'Incident register',
    singular: 'incident',
    fields: [
      {
        key: 'title',
        label: 'Incident reference / title',
        type: 'text',
        required: true,
        column: 'title',
      },
      {
        key: 'occurredAt',
        label: 'Occurred',
        type: 'datetime-local',
        required: true,
        column: 'occurred_at',
      },
      {
        key: 'studentId',
        label: 'Student',
        type: 'reference',
        required: false,
        reference: 'students',
        column: 'student_id',
      },
      {
        key: 'staffId',
        label: 'Supervising staff',
        type: 'reference',
        required: false,
        reference: 'staff',
        column: 'staff_id',
      },
      {
        key: 'venueId',
        label: 'Venue',
        type: 'reference',
        required: false,
        reference: 'venues',
        column: 'venue_id',
      },
      {
        key: 'classId',
        label: 'Class',
        type: 'reference',
        required: false,
        reference: 'classes',
        column: 'class_id',
      },
      {
        key: 'eventId',
        label: 'Event',
        type: 'reference',
        required: false,
        reference: 'events',
        column: 'event_id',
      },
      {
        key: 'category',
        label: 'Incident type',
        type: 'text',
        required: true,
        column: 'category',
      },
      {
        key: 'sport',
        label: 'Sport / activity',
        type: 'text',
        required: false,
        column: 'sport',
      },
      {
        key: 'severity',
        label: 'Severity',
        type: 'select',
        required: true,
        options: ['low', 'medium', 'high', 'critical'],
        defaultValue: 'low',
        column: 'severity',
      },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: ['open', 'in_progress', 'resolved', 'closed'],
        defaultValue: 'open',
        column: 'status',
      },
      {
        key: 'secureNote',
        label: 'Confidential incident details',
        type: 'encrypted',
        required: true,
        column: 'secure_note',
      },
    ],
    existing: false,
  },
  {
    name: 'hazards',
    table: 'hazards',
    module: 'risk',
    title: 'Hazards & controls',
    singular: 'hazard',
    fields: [
      {
        key: 'title',
        label: 'Hazard',
        type: 'text',
        required: true,
        column: 'title',
      },
      {
        key: 'venueId',
        label: 'Venue',
        type: 'reference',
        required: false,
        reference: 'venues',
        column: 'venue_id',
      },
      {
        key: 'roomId',
        label: 'Room',
        type: 'reference',
        required: false,
        reference: 'rooms',
        column: 'room_id',
      },
      {
        key: 'category',
        label: 'Category',
        type: 'text',
        required: true,
        column: 'category',
      },
      {
        key: 'likelihood',
        label: 'Likelihood (1\u20135)',
        type: 'number',
        required: true,
        min: 1,
        max: 5,
        column: 'likelihood',
      },
      {
        key: 'impact',
        label: 'Impact (1\u20135)',
        type: 'number',
        required: true,
        min: 1,
        max: 5,
        column: 'impact',
      },
      {
        key: 'controls',
        label: 'Control measures',
        type: 'textarea',
        required: true,
        column: 'controls',
      },
      {
        key: 'ownerUserId',
        label: 'Owner',
        type: 'reference',
        required: false,
        reference: 'users',
        column: 'owner_user_id',
      },
      {
        key: 'reviewOn',
        label: 'Next review',
        type: 'date',
        required: true,
        column: 'review_on',
      },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: ['identified', 'controlled', 'review_due', 'closed'],
        defaultValue: 'identified',
        column: 'status',
      },
    ],
    existing: false,
  },
  {
    name: 'safety-drills',
    table: 'safety_drills',
    module: 'risk',
    title: 'Fire, evacuation & lockdown',
    singular: 'safety record',
    fields: [
      {
        key: 'campusId',
        label: 'Campus',
        type: 'reference',
        required: true,
        reference: 'campuses',
        column: 'campus_id',
      },
      {
        key: 'kind',
        label: 'Record type',
        type: 'select',
        required: true,
        options: ['fire_inspection', 'evacuation', 'lockdown', 'equipment_check'],
        defaultValue: 'fire_inspection',
        column: 'kind',
      },
      {
        key: 'title',
        label: 'Title',
        type: 'text',
        required: true,
        column: 'title',
      },
      {
        key: 'scheduledAt',
        label: 'Scheduled',
        type: 'datetime-local',
        required: true,
        column: 'scheduled_at',
      },
      {
        key: 'completedAt',
        label: 'Completed',
        type: 'datetime-local',
        required: false,
        column: 'completed_at',
      },
      {
        key: 'assemblyPoint',
        label: 'Assembly point',
        type: 'text',
        required: false,
        column: 'assembly_point',
      },
      {
        key: 'findings',
        label: 'Findings / actions',
        type: 'textarea',
        required: false,
        column: 'findings',
      },
      {
        key: 'ownerUserId',
        label: 'Owner',
        type: 'reference',
        required: false,
        reference: 'users',
        column: 'owner_user_id',
      },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: ['planned', 'in_progress', 'complete', 'actions_required'],
        defaultValue: 'planned',
        column: 'status',
      },
    ],
    existing: false,
  },
  {
    name: 'nurse-visits',
    table: 'nurse_visits',
    module: 'nurse',
    title: 'Nurse visits',
    singular: 'visit',
    fields: [
      {
        key: 'studentId',
        label: 'Student',
        type: 'reference',
        required: true,
        reference: 'students',
        column: 'student_id',
      },
      {
        key: 'arrivedAt',
        label: 'Arrival',
        type: 'datetime-local',
        required: true,
        column: 'arrived_at',
      },
      {
        key: 'departedAt',
        label: 'Departure',
        type: 'datetime-local',
        required: false,
        column: 'departed_at',
      },
      {
        key: 'outcome',
        label: 'Outcome',
        type: 'select',
        required: true,
        options: ['in_care', 'returned_to_class', 'collected', 'ambulance', 'referred'],
        defaultValue: 'in_care',
        column: 'outcome',
      },
      {
        key: 'parentContacted',
        label: 'Parent contacted',
        type: 'boolean',
        required: false,
        column: 'parent_contacted',
      },
      {
        key: 'secureNote',
        label: 'Assessment, care & follow-up',
        type: 'encrypted',
        required: true,
        column: 'secure_note',
      },
    ],
    existing: false,
  },
  {
    name: 'wellbeing-cases',
    table: 'wellbeing_cases',
    module: 'wellbeing',
    title: 'Wellbeing & counselling',
    singular: 'case',
    fields: [
      {
        key: 'studentId',
        label: 'Student',
        type: 'reference',
        required: true,
        reference: 'students',
        column: 'student_id',
      },
      {
        key: 'assignedUserId',
        label: 'Assigned practitioner',
        type: 'reference',
        required: true,
        reference: 'users',
        column: 'assigned_user_id',
      },
      {
        key: 'category',
        label: 'Support type',
        type: 'select',
        required: true,
        options: ['wellbeing', 'counselling', 'psychology', 'pastoral', 'referral'],
        defaultValue: 'wellbeing',
        column: 'category',
      },
      {
        key: 'openedOn',
        label: 'Opened',
        type: 'date',
        required: true,
        column: 'opened_on',
      },
      {
        key: 'reviewOn',
        label: 'Next review',
        type: 'date',
        required: true,
        column: 'review_on',
      },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: ['open', 'monitoring', 'referred', 'closed'],
        defaultValue: 'open',
        column: 'status',
      },
      {
        key: 'secureNote',
        label: 'Confidential case notes',
        type: 'encrypted',
        required: true,
        column: 'secure_note',
      },
    ],
    existing: false,
    assignedOnly: true,
  },
  {
    name: 'buildings',
    table: 'buildings',
    module: 'maintenance',
    title: 'Buildings',
    singular: 'building',
    fields: [
      {
        key: 'campusId',
        label: 'Campus',
        type: 'reference',
        required: true,
        reference: 'campuses',
        column: 'campus_id',
      },
      {
        key: 'code',
        label: 'Code',
        type: 'text',
        required: true,
        column: 'code',
      },
      {
        key: 'name',
        label: 'Name',
        type: 'text',
        required: true,
        column: 'name',
      },
      {
        key: 'address',
        label: 'Address',
        type: 'textarea',
        required: false,
        column: 'address',
      },
      {
        key: 'accessNotes',
        label: 'Access requirements',
        type: 'textarea',
        required: false,
        column: 'access_notes',
      },
      {
        key: 'active',
        label: 'Active',
        type: 'boolean',
        required: false,
        defaultValue: true,
        column: 'active',
      },
    ],
    existing: false,
  },
  {
    name: 'rooms',
    table: 'rooms',
    module: 'maintenance',
    title: 'Rooms & facilities',
    singular: 'room',
    fields: [
      {
        key: 'campusId',
        label: 'Campus',
        type: 'reference',
        required: true,
        reference: 'campuses',
        column: 'campus_id',
      },
      {
        key: 'code',
        label: 'Code',
        type: 'text',
        required: true,
        column: 'code',
      },
      {
        key: 'name',
        label: 'Name',
        type: 'text',
        required: true,
        column: 'name',
      },
      {
        key: 'capacity',
        label: 'Capacity',
        type: 'number',
        required: false,
        min: 1,
        max: 10000,
        column: 'capacity',
      },
      {
        key: 'accessible',
        label: 'Accessible',
        type: 'boolean',
        required: false,
        defaultValue: true,
        column: 'accessible',
      },
      {
        key: 'active',
        label: 'Active',
        type: 'boolean',
        required: false,
        defaultValue: true,
        column: 'active',
      },
    ],
    existing: true,
  },
  {
    name: 'work-orders',
    table: 'work_orders',
    module: 'maintenance',
    title: 'Maintenance & capital works',
    singular: 'work order',
    fields: [
      {
        key: 'title',
        label: 'Work required',
        type: 'text',
        required: true,
        column: 'title',
      },
      {
        key: 'buildingId',
        label: 'Building',
        type: 'reference',
        required: false,
        reference: 'buildings',
        column: 'building_id',
      },
      {
        key: 'roomId',
        label: 'Room',
        type: 'reference',
        required: false,
        reference: 'rooms',
        column: 'room_id',
      },
      {
        key: 'category',
        label: 'Work type',
        type: 'select',
        required: true,
        options: ['repair', 'inspection', 'grounds', 'capital_works', 'construction', 'renovation'],
        defaultValue: 'repair',
        column: 'category',
      },
      {
        key: 'priority',
        label: 'Priority',
        type: 'select',
        required: true,
        options: ['routine', 'urgent', 'critical'],
        defaultValue: 'routine',
        column: 'priority',
      },
      {
        key: 'description',
        label: 'Scope of work',
        type: 'textarea',
        required: true,
        column: 'description',
      },
      {
        key: 'assignedUserId',
        label: 'Assigned to',
        type: 'reference',
        required: false,
        reference: 'users',
        column: 'assigned_user_id',
      },
      {
        key: 'dueOn',
        label: 'Due date',
        type: 'date',
        required: true,
        column: 'due_on',
      },
      {
        key: 'completedOn',
        label: 'Completed',
        type: 'date',
        required: false,
        column: 'completed_on',
      },
      {
        key: 'cost',
        label: 'Cost (AUD)',
        type: 'money',
        required: false,
        defaultValue: '0.00',
        column: 'cost',
      },
      {
        key: 'accountId',
        label: 'GL account',
        type: 'reference',
        required: false,
        reference: 'finance-accounts',
        column: 'account_id',
      },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: ['open', 'assigned', 'in_progress', 'completed', 'cancelled'],
        defaultValue: 'open',
        column: 'status',
      },
    ],
    existing: false,
  },
  {
    name: 'maintenance-history',
    table: 'maintenance_history',
    module: 'maintenance',
    title: 'Maintenance history',
    singular: 'service record',
    fields: [
      {
        key: 'workOrderId',
        label: 'Work order',
        type: 'reference',
        required: true,
        reference: 'work-orders',
        column: 'work_order_id',
      },
      {
        key: 'performedAt',
        label: 'Performed',
        type: 'datetime-local',
        required: true,
        column: 'performed_at',
      },
      {
        key: 'summary',
        label: 'Work performed',
        type: 'textarea',
        required: true,
        column: 'summary',
      },
      {
        key: 'contractor',
        label: 'Contractor',
        type: 'text',
        required: false,
        column: 'contractor',
      },
      {
        key: 'cost',
        label: 'Cost (AUD)',
        type: 'money',
        required: true,
        column: 'cost',
      },
      {
        key: 'nextDueOn',
        label: 'Next service',
        type: 'date',
        required: false,
        column: 'next_due_on',
      },
    ],
    existing: false,
  },
  {
    name: 'suppliers',
    table: 'suppliers',
    module: 'finance',
    title: 'Suppliers',
    singular: 'supplier',
    fields: [
      {
        key: 'name',
        label: 'Supplier name',
        type: 'text',
        required: true,
        column: 'name',
      },
      {
        key: 'abn',
        label: 'ABN',
        type: 'text',
        required: false,
        column: 'abn',
      },
      {
        key: 'email',
        label: 'Email',
        type: 'email',
        required: false,
        column: 'email',
      },
      {
        key: 'phone',
        label: 'Phone',
        type: 'text',
        required: false,
        column: 'phone',
      },
      {
        key: 'address',
        label: 'Address',
        type: 'textarea',
        required: false,
        column: 'address',
      },
      {
        key: 'paymentTermsDays',
        label: 'Payment terms (days)',
        type: 'number',
        required: true,
        min: 0,
        max: 365,
        defaultValue: 30,
        column: 'payment_terms_days',
      },
      {
        key: 'active',
        label: 'Active',
        type: 'boolean',
        required: false,
        defaultValue: true,
        column: 'active',
      },
    ],
    existing: false,
  },
  {
    name: 'purchase-orders',
    table: 'purchase_orders',
    module: 'finance',
    title: 'Purchase orders',
    singular: 'purchase order',
    fields: [
      {
        key: 'reference',
        label: 'PO reference',
        type: 'text',
        required: true,
        column: 'reference',
      },
      {
        key: 'supplierId',
        label: 'Supplier',
        type: 'reference',
        required: true,
        reference: 'suppliers',
        column: 'supplier_id',
      },
      {
        key: 'accountId',
        label: 'Expense / asset GL',
        type: 'reference',
        required: true,
        reference: 'finance-accounts',
        column: 'account_id',
      },
      {
        key: 'budgetId',
        label: 'Budget',
        type: 'reference',
        required: false,
        reference: 'budgets',
        column: 'budget_id',
      },
      {
        key: 'description',
        label: 'What is being purchased',
        type: 'textarea',
        required: true,
        column: 'description',
      },
      {
        key: 'amount',
        label: 'Amount excluding GST',
        type: 'money',
        required: true,
        column: 'amount',
      },
      {
        key: 'taxTotal',
        label: 'GST',
        type: 'money',
        required: true,
        defaultValue: '0.00',
        column: 'tax_total',
      },
      {
        key: 'dueOn',
        label: 'Required by',
        type: 'date',
        required: true,
        column: 'due_on',
      },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: [
          'draft',
          'submitted',
          'approved',
          'received',
          'invoiced',
          'paid',
          'rejected',
          'cancelled',
        ],
        defaultValue: 'draft',
        column: 'status',
      },
    ],
    existing: false,
    workflow: true,
  },
  {
    name: 'supplier-bills',
    table: 'supplier_bills',
    module: 'finance',
    title: 'Accounts payable',
    singular: 'supplier bill',
    fields: [
      {
        key: 'purchaseOrderId',
        label: 'Approved purchase order',
        type: 'reference',
        required: true,
        reference: 'purchase-orders',
        column: 'purchase_order_id',
      },
      {
        key: 'supplierId',
        label: 'Supplier',
        type: 'reference',
        required: true,
        reference: 'suppliers',
        column: 'supplier_id',
      },
      {
        key: 'reference',
        label: 'Supplier invoice number',
        type: 'text',
        required: true,
        column: 'reference',
      },
      {
        key: 'issueDate',
        label: 'Invoice date',
        type: 'date',
        required: true,
        column: 'issue_date',
      },
      {
        key: 'dueDate',
        label: 'Due date',
        type: 'date',
        required: true,
        column: 'due_date',
      },
      {
        key: 'amount',
        label: 'Amount excluding GST',
        type: 'money',
        required: true,
        column: 'amount',
      },
      {
        key: 'taxTotal',
        label: 'GST',
        type: 'money',
        required: true,
        column: 'tax_total',
      },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: ['draft', 'matched', 'approved', 'paid', 'disputed'],
        defaultValue: 'draft',
        column: 'status',
      },
    ],
    existing: false,
    workflow: true,
  },
  {
    name: 'fee-policies',
    table: 'fee_policies',
    module: 'finance',
    title: 'Scholarships & sibling discounts',
    singular: 'fee policy',
    fields: [
      {
        key: 'name',
        label: 'Policy name',
        type: 'text',
        required: true,
        column: 'name',
      },
      {
        key: 'kind',
        label: 'Policy type',
        type: 'select',
        required: true,
        options: ['sibling_discount', 'scholarship', 'fee_split', 'bursary'],
        defaultValue: 'sibling_discount',
        column: 'kind',
      },
      {
        key: 'familyId',
        label: 'Family',
        type: 'reference',
        required: false,
        reference: 'families',
        column: 'family_id',
      },
      {
        key: 'studentId',
        label: 'Student',
        type: 'reference',
        required: false,
        reference: 'students',
        column: 'student_id',
      },
      {
        key: 'guardianId',
        label: 'Responsible guardian',
        type: 'reference',
        required: false,
        reference: 'guardians',
        column: 'guardian_id',
      },
      {
        key: 'percent',
        label: 'Percentage',
        type: 'number',
        required: true,
        min: 0,
        max: 100,
        column: 'percent',
      },
      {
        key: 'minimumSiblings',
        label: 'Minimum enrolled siblings',
        type: 'number',
        required: false,
        min: 1,
        max: 30,
        column: 'minimum_siblings',
      },
      {
        key: 'startsOn',
        label: 'Starts',
        type: 'date',
        required: true,
        column: 'starts_on',
      },
      {
        key: 'endsOn',
        label: 'Ends',
        type: 'date',
        required: true,
        column: 'ends_on',
      },
      {
        key: 'notes',
        label: 'Decision / eligibility',
        type: 'textarea',
        required: false,
        column: 'notes',
      },
      {
        key: 'active',
        label: 'Active',
        type: 'boolean',
        required: false,
        defaultValue: true,
        column: 'active',
      },
    ],
    existing: false,
  },
  {
    name: 'bank-accounts',
    table: 'bank_accounts',
    module: 'finance',
    title: 'Bank accounts',
    singular: 'bank account',
    fields: [
      {
        key: 'name',
        label: 'Account name',
        type: 'text',
        required: true,
        column: 'name',
      },
      {
        key: 'accountId',
        label: 'Bank GL account',
        type: 'reference',
        required: true,
        reference: 'finance-accounts',
        column: 'account_id',
      },
      {
        key: 'currencyCode',
        label: 'Currency',
        type: 'text',
        required: true,
        defaultValue: 'AUD',
        column: 'currency_code',
      },
      {
        key: 'statementReference',
        label: 'Masked account reference',
        type: 'text',
        required: false,
        column: 'statement_reference',
      },
      {
        key: 'active',
        label: 'Active',
        type: 'boolean',
        required: false,
        defaultValue: true,
        column: 'active',
      },
    ],
    existing: false,
  },
  {
    name: 'bank-transactions',
    table: 'bank_transactions',
    module: 'finance',
    title: 'Bank reconciliation',
    singular: 'bank transaction',
    fields: [
      {
        key: 'bankAccountId',
        label: 'Bank account',
        type: 'reference',
        required: true,
        reference: 'bank-accounts',
        column: 'bank_account_id',
      },
      {
        key: 'reference',
        label: 'Statement reference',
        type: 'text',
        required: true,
        column: 'reference',
      },
      {
        key: 'transactionDate',
        label: 'Transaction date',
        type: 'date',
        required: true,
        column: 'transaction_date',
      },
      {
        key: 'description',
        label: 'Description',
        type: 'textarea',
        required: true,
        column: 'description',
      },
      {
        key: 'amount',
        label: 'Signed amount',
        type: 'money',
        required: true,
        signed: true,
        column: 'amount',
      },
      {
        key: 'paymentId',
        label: 'Match to receipt',
        type: 'reference',
        required: false,
        reference: 'payments',
        column: 'payment_id',
      },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: ['unmatched', 'matched', 'reconciled'],
        defaultValue: 'unmatched',
        column: 'status',
      },
    ],
    existing: false,
    workflow: true,
  },
  {
    name: 'budgets',
    table: 'budgets',
    module: 'finance',
    title: 'Budgets',
    singular: 'budget',
    fields: [
      {
        key: 'academicYearId',
        label: 'Academic year',
        type: 'reference',
        required: true,
        reference: 'academic-years',
        column: 'academic_year_id',
      },
      {
        key: 'accountId',
        label: 'GL account',
        type: 'reference',
        required: true,
        reference: 'finance-accounts',
        column: 'account_id',
      },
      {
        key: 'campusId',
        label: 'Campus',
        type: 'reference',
        required: false,
        reference: 'campuses',
        column: 'campus_id',
      },
      {
        key: 'departmentId',
        label: 'Department',
        type: 'reference',
        required: false,
        reference: 'departments',
        column: 'department_id',
      },
      {
        key: 'amount',
        label: 'Budget amount',
        type: 'money',
        required: true,
        column: 'amount',
      },
      {
        key: 'notes',
        label: 'Notes',
        type: 'textarea',
        required: false,
        column: 'notes',
      },
    ],
    existing: true,
  },
  {
    name: 'payments',
    table: 'payments',
    module: 'finance',
    title: 'Customer receipts',
    singular: 'receipt',
    fields: [
      {
        key: 'invoiceId',
        label: 'Invoice',
        type: 'reference',
        required: false,
        reference: 'invoices',
        column: 'invoice_id',
      },
      {
        key: 'paymentReference',
        label: 'Receipt reference',
        type: 'text',
        required: true,
        column: 'payment_reference',
      },
      {
        key: 'receivedAt',
        label: 'Received',
        type: 'datetime-local',
        required: true,
        column: 'received_at',
      },
      {
        key: 'amount',
        label: 'Amount received',
        type: 'money',
        required: true,
        column: 'amount',
      },
      {
        key: 'currencyCode',
        label: 'Currency',
        type: 'text',
        required: true,
        defaultValue: 'AUD',
        column: 'currency_code',
      },
      {
        key: 'method',
        label: 'Method',
        type: 'select',
        required: true,
        options: ['bank_transfer', 'cash', 'cheque', 'gateway'],
        defaultValue: 'bank_transfer',
        column: 'method',
      },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: ['pending', 'settled', 'refunded', 'failed'],
        defaultValue: 'pending',
        column: 'status',
      },
      {
        key: 'invoiceAllocationId',
        column: 'invoice_allocation_id',
        label: 'Guardian invoice allocation (required for split invoices)',
        type: 'reference',
        reference: 'invoice-allocations',
        required: false,
      },
    ],
    existing: true,
    workflow: true,
  },
  {
    name: 'payroll-lines',
    table: 'payroll_lines',
    module: 'finance',
    title: 'Payroll & timetable overtime',
    singular: 'payroll line',
    fields: [
      {
        key: 'staffId',
        label: 'Staff member',
        type: 'reference',
        required: true,
        reference: 'staff',
        column: 'staff_id',
      },
      {
        key: 'periodStart',
        label: 'Pay period starts',
        type: 'date',
        required: true,
        column: 'period_start',
      },
      {
        key: 'periodEnd',
        label: 'Pay period ends',
        type: 'date',
        required: true,
        column: 'period_end',
      },
      {
        key: 'ordinaryMinutes',
        label: 'Ordinary minutes',
        type: 'number',
        required: true,
        min: 0,
        max: 50000,
        column: 'ordinary_minutes',
      },
      {
        key: 'overtimeMinutes',
        label: 'Approved overtime minutes',
        type: 'number',
        required: true,
        min: 0,
        max: 50000,
        defaultValue: 0,
        column: 'overtime_minutes',
      },
      {
        key: 'hourlyRate',
        label: 'Ordinary hourly rate',
        type: 'money',
        required: true,
        column: 'hourly_rate',
      },
      {
        key: 'overtimeRate',
        label: 'Overtime hourly rate',
        type: 'money',
        required: true,
        column: 'overtime_rate',
      },
      {
        key: 'taxTotal',
        label: 'Approved withholding amount',
        type: 'money',
        required: true,
        defaultValue: '0.00',
        column: 'tax_total',
      },
      {
        key: 'notes',
        label: 'Payroll review notes',
        type: 'textarea',
        required: false,
        column: 'notes',
      },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: ['draft', 'submitted', 'approved', 'paid'],
        defaultValue: 'draft',
        column: 'status',
      },
    ],
    existing: false,
    workflow: true,
  },
  {
    name: 'staff-onboarding',
    table: 'staff_onboarding',
    module: 'staff',
    title: 'Staff onboarding & training',
    singular: 'onboarding task',
    fields: [
      {
        key: 'staffId',
        label: 'Staff member',
        type: 'reference',
        required: true,
        reference: 'staff',
        column: 'staff_id',
      },
      {
        key: 'title',
        label: 'Task / training',
        type: 'text',
        required: true,
        column: 'title',
      },
      {
        key: 'kind',
        label: 'Task type',
        type: 'select',
        required: true,
        options: [
          'identity_check',
          'child_safety',
          'induction',
          'training',
          'payroll',
          'system_access',
        ],
        defaultValue: 'identity_check',
        column: 'kind',
      },
      {
        key: 'assignedUserId',
        label: 'Responsible user',
        type: 'reference',
        required: false,
        reference: 'users',
        column: 'assigned_user_id',
      },
      {
        key: 'dueOn',
        label: 'Due date',
        type: 'date',
        required: true,
        column: 'due_on',
      },
      {
        key: 'completedOn',
        label: 'Completed',
        type: 'date',
        required: false,
        column: 'completed_on',
      },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: ['pending', 'in_progress', 'completed', 'blocked'],
        defaultValue: 'pending',
        column: 'status',
      },
    ],
    existing: false,
  },
  {
    name: 'report-templates',
    table: 'report_templates',
    module: 'finance',
    title: 'Report & invoice templates',
    singular: 'template',
    fields: [
      {
        key: 'name',
        label: 'Template name',
        type: 'text',
        required: true,
        column: 'name',
      },
      {
        key: 'kind',
        label: 'Template type',
        type: 'select',
        required: true,
        options: ['invoice', 'income_statement', 'balance_sheet', 'budget', 'general'],
        defaultValue: 'invoice',
        column: 'kind',
      },
      {
        key: 'heading',
        label: 'Heading',
        type: 'text',
        required: true,
        column: 'heading',
      },
      {
        key: 'footer',
        label: 'Footer',
        type: 'textarea',
        required: false,
        column: 'footer',
      },
      {
        key: 'accentColour',
        label: 'Accent colour',
        type: 'colour',
        required: false,
        defaultValue: '#0f6cbd',
        column: 'accent_colour',
      },
      {
        key: 'organisationDetails',
        label: 'Organisation details',
        type: 'textarea',
        required: false,
        column: 'organisation_details',
      },
      {
        key: 'paymentInstructions',
        label: 'Payment instructions',
        type: 'textarea',
        required: false,
        column: 'payment_instructions',
      },
    ],
    existing: false,
  },
  {
    name: 'alumni-donations',
    table: 'alumni_donations',
    module: 'alumni',
    title: 'Donations',
    singular: 'donation',
    fields: [
      {
        key: 'alumniProfileId',
        label: 'Alumni profile',
        type: 'reference',
        required: true,
        reference: 'alumni',
        column: 'alumni_profile_id',
      },
      {
        key: 'reference',
        label: 'Receipt / pledge reference',
        type: 'text',
        required: true,
        column: 'reference',
      },
      {
        key: 'receivedOn',
        label: 'Received / pledged',
        type: 'date',
        required: true,
        column: 'received_on',
      },
      {
        key: 'amount',
        label: 'Amount (AUD)',
        type: 'money',
        required: true,
        column: 'amount',
      },
      {
        key: 'purpose',
        label: 'Purpose',
        type: 'text',
        required: true,
        column: 'purpose',
      },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: ['pledged', 'received', 'refunded'],
        defaultValue: 'pledged',
        column: 'status',
      },
      {
        key: 'acknowledged',
        label: 'Acknowledged',
        type: 'boolean',
        required: false,
        column: 'acknowledged',
      },
    ],
    existing: false,
  },
  {
    name: 'alumni-events',
    table: 'alumni_events',
    module: 'alumni',
    title: 'Alumni events',
    singular: 'alumni event',
    fields: [
      {
        key: 'eventId',
        label: 'School event',
        type: 'reference',
        required: true,
        reference: 'events',
        column: 'event_id',
      },
      {
        key: 'title',
        label: 'Title',
        type: 'text',
        required: true,
        column: 'title',
      },
      {
        key: 'classOf',
        label: 'Graduation years',
        type: 'tags',
        required: false,
        column: 'class_of',
      },
      {
        key: 'groupId',
        label: 'Network / group',
        type: 'reference',
        required: false,
        reference: 'school-groups',
        column: 'group_id',
      },
      {
        key: 'notes',
        label: 'Notes',
        type: 'textarea',
        required: false,
        column: 'notes',
      },
    ],
    existing: false,
  },
  {
    name: 'alumni-family-links',
    table: 'alumni_family_links',
    module: 'alumni',
    title: 'Alumni & current families',
    singular: 'family link',
    fields: [
      {
        key: 'alumniProfileId',
        label: 'Alumni profile',
        type: 'reference',
        required: true,
        reference: 'alumni',
        column: 'alumni_profile_id',
      },
      {
        key: 'familyId',
        label: 'Current family',
        type: 'reference',
        required: true,
        reference: 'families',
        column: 'family_id',
      },
      {
        key: 'relationship',
        label: 'Relationship',
        type: 'text',
        required: true,
        column: 'relationship',
      },
      {
        key: 'verifiedOn',
        label: 'Verified',
        type: 'date',
        required: true,
        column: 'verified_on',
      },
    ],
    existing: false,
  },
  {
    name: 'course-materials',
    table: 'course_materials',
    module: 'classes',
    title: 'Course materials',
    singular: 'course material',
    fields: [
      {
        key: 'classId',
        label: 'Class',
        type: 'reference',
        required: true,
        reference: 'classes',
        column: 'class_id',
      },
      {
        key: 'title',
        label: 'Title',
        type: 'text',
        required: true,
        column: 'title',
      },
      {
        key: 'description',
        label: 'Description',
        type: 'textarea',
        required: false,
        column: 'description',
      },
      {
        key: 'content',
        label: 'Learning material',
        type: 'textarea',
        required: true,
        column: 'content',
      },
      {
        key: 'language',
        label: 'Language',
        type: 'text',
        required: true,
        defaultValue: 'en-AU',
        column: 'language',
      },
      {
        key: 'subject',
        label: 'Subject metadata',
        type: 'text',
        required: false,
        column: 'subject',
      },
      {
        key: 'licence',
        label: 'Licence / rights',
        type: 'text',
        required: false,
        column: 'licence',
      },
      {
        key: 'resourceType',
        label: 'Learning resource type',
        type: 'text',
        required: true,
        defaultValue: 'lesson',
        column: 'resource_type',
      },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: ['draft', 'published', 'archived'],
        defaultValue: 'draft',
        column: 'status',
      },
    ],
    existing: false,
  },
  {
    name: 'assignments',
    table: 'assignments',
    module: 'classes',
    title: 'Assignments',
    singular: 'assignment',
    fields: [
      {
        key: 'classId',
        label: 'Class',
        type: 'reference',
        required: true,
        reference: 'classes',
        column: 'class_id',
      },
      {
        key: 'title',
        label: 'Title',
        type: 'text',
        required: true,
        column: 'title',
      },
      {
        key: 'instructions',
        label: 'Instructions',
        type: 'textarea',
        required: true,
        column: 'instructions',
      },
      {
        key: 'dueAt',
        label: 'Due',
        type: 'datetime-local',
        required: true,
        column: 'due_at',
      },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: ['draft', 'published', 'closed'],
        defaultValue: 'draft',
        column: 'status',
      },
    ],
    existing: false,
  },
  {
    name: 'guardian-relationships',
    table: 'guardian_relationships',
    module: 'families',
    title: 'Family relationships & contact access',
    singular: 'relationship',
    fields: [
      {
        key: 'guardianId',
        label: 'Guardian',
        type: 'reference',
        required: true,
        reference: 'guardians',
        column: 'guardian_id',
      },
      {
        key: 'studentId',
        label: 'Student',
        type: 'reference',
        required: true,
        reference: 'students',
        column: 'student_id',
      },
      {
        key: 'relationship',
        label: 'Relationship label',
        type: 'text',
        required: true,
        column: 'relationship',
      },
      {
        key: 'canViewMedical',
        label: 'May view medical record',
        type: 'boolean',
        required: false,
        column: 'can_view_medical',
      },
      {
        key: 'canConsent',
        label: 'May provide consent',
        type: 'boolean',
        required: false,
        column: 'can_consent',
      },
      {
        key: 'canViewFinance',
        label: 'May view allocated invoices',
        type: 'boolean',
        required: false,
        column: 'can_view_finance',
      },
      {
        key: 'receivesComms',
        label: 'Receives correspondence',
        type: 'boolean',
        required: false,
        defaultValue: true,
        column: 'receives_comms',
      },
      {
        key: 'restricted',
        label: 'Contact restriction applies',
        type: 'boolean',
        required: false,
        column: 'restricted',
      },
      {
        key: 'validFrom',
        label: 'Valid from',
        type: 'date',
        required: true,
        column: 'valid_from',
      },
      {
        key: 'validUntil',
        label: 'Valid until',
        type: 'date',
        required: false,
        column: 'valid_until',
      },
    ],
    existing: false,
    adminOnly: true,
  },
];
export const roadmapResourceNames = [
  'invoice-allocations',
  'guardians',
  'class-rosters',
  'class-teachers',
  'timetable-entries',
  'event-participants',
  'grade-results',
  'attendance-sessions',
  'family-students',
  'portal-contacts',
  'campuses',
  'academic-years',
  'terms',
  'bell-periods',
  'important-dates',
  'school-groups',
  'group-members',
  'departments',
  'venues',
  'event-plans',
  'event-templates',
  'event-risks',
  'approval-streams',
  'event-access',
  'risk-incidents',
  'hazards',
  'safety-drills',
  'nurse-visits',
  'wellbeing-cases',
  'buildings',
  'rooms',
  'work-orders',
  'maintenance-history',
  'suppliers',
  'purchase-orders',
  'supplier-bills',
  'fee-policies',
  'bank-accounts',
  'bank-transactions',
  'budgets',
  'payments',
  'payroll-lines',
  'staff-onboarding',
  'report-templates',
  'alumni-donations',
  'alumni-events',
  'alumni-family-links',
  'course-materials',
  'assignments',
  'guardian-relationships',
] as const;

/** Validates a field without interpreting strings as code, SQL, markup, or arbitrary expressions. */
export function roadmapFieldSchema(field: RoadmapField): z.ZodType {
  let schema: z.ZodType;
  switch (field.type) {
    case 'reference':
      schema = z.uuid();
      break;
    case 'date':
      schema = z.iso.date();
      break;
    case 'datetime-local':
      schema = z.iso.datetime();
      break;
    case 'time':
      schema = z.string().regex(/^([01]\d|2[0-3]):[0-5]\d(:[0-5]\d)?$/);
      break;
    case 'email':
      schema = z.email();
      break;
    case 'number':
      schema = z
        .number()
        .int()
        .min(field.min ?? 0)
        .max(field.max ?? 100000000);
      break;
    case 'money':
      schema = z
        .union([z.string(), z.number()])
        .transform(
          /** Keeps decimal precision explicit at the API boundary. */ (value) => String(value),
        )
        .pipe(
          z.string().regex(field.signed ? /^-?\d{1,10}(\.\d{1,2})?$/ : /^\d{1,10}(\.\d{1,2})?$/),
        );
      break;
    case 'boolean':
      schema = z.boolean();
      break;
    case 'select':
      schema = z.enum(field.options as [string, ...string[]]);
      break;
    case 'tags':
      schema = z.array(z.string().trim().min(1).max(100)).max(50);
      break;
    case 'colour':
      schema = z.string().regex(/^#[0-9a-fA-F]{6}$/);
      break;
    case 'encrypted':
      schema = z
        .object({
          version: z.literal(1),
          keyId: z.uuid(),
          algorithm: z.literal('AES-256-GCM'),
          iv: z.base64().length(16),
          ciphertext: z.base64().min(24).max(180000),
        })
        .strict();
      break;
    default:
      schema = z
        .string()
        .trim()
        .min(field.required ? 1 : 0)
        .max(field.type === 'textarea' ? 20000 : 240);
  }
  return field.required ? schema : schema.nullable();
}
